ALTER TABLE cotacoes
  ADD COLUMN IF NOT EXISTS valor_fechamento DECIMAL(12,2),
  ADD COLUMN IF NOT EXISTS data_prevista_fechamento DATE;

ALTER TABLE item_cotacao
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE
    DEFAULT CURRENT_TIMESTAMP NOT NULL;
