export const API = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    refresh: "/auth/refresh-token",
    logout: "/auth/logout",
    me: "/auth/me",
    changePassword: "/auth/change-password",
    setup2fa: "/auth/2fa/setup",
    confirm2fa: "/auth/2fa/confirm",
  },
  orders: {
    list: "/pedidos",
    create: "/pedidos",
    detail: (id: string) => `/pedidos/${id}`,
    update: (id: string) => `/pedidos/${id}`,
    status: (id: string) => `/pedidos/${id}/status`,
    delete: (id: string) => `/pedidos/${id}`,
    history: (id: string) => `/pedidos/${id}/history`,
    items: (id: string) => `/pedidos/${id}/items`,
    itemStatus: (id: string, itemId: string) => `/pedidos/${id}/items/${itemId}/status`,
    costs: (id: string) => `/pedidos/${id}/costs`,
    payments: (id: string) => `/pedidos/${id}/payment-methods`,
  },
  quotes: {
    list: "/quotes",
    create: "/quotes",
    detail: (id: string) => `/quotes/${id}`,
    update: (id: string) => `/quotes/${id}`,
    phase: (id: string) => `/quotes/${id}/phase`,
    delete: (id: string) => `/quotes/${id}`,
    convert: (id: string) => `/quotes/${id}/convert`,
  },
  rma: {
    list: "/rma",
    create: "/rma",
    detail: (id: string) => `/rma/${id}`,
    close: (id: string) => `/rma/${id}/close`,
    itemStatus: (id: string, itemId: string) => `/rma/${id}/items/${itemId}/status`,
  },
  users: {
    list: "/users",
    me: "/users/me",
    detail: (id: string) => `/users/${id}`,
    deactivate: (id: string) => `/users/${id}/deactivate`,
    export: (id: string) => `/users/${id}/data-export`,
    deleteData: (id: string) => `/users/${id}/delete-data`,
  },
} as const
